[tool.poetry]
name = "laba18"
version = "0.1.0"
description = ""
authors = ["internetHacker1123 <dinozavrik9911@mail.ru>"]
readme = "README.md"

[tool.poetry.dependencies]
python = "^3.11"


[build-system]
requires = ["poetry-core"]
build-backend = "poetry.core.masonry.api"
